### ISSUE TITLE
Exit button doesn't work.

### ISSUE THREAD

**Issue by Derpyface** [Derpyface-Development-Co/Craft-Clash#3]
When I click on the *Exit* button the program freezes for a while and then re-opens. Sometimes the program gets permanently frozen when I click the *Exit* button so I have to kill the program.

This is very frustrating, any help?

**Comment by Derpyface** [comment]
Just click the RED *X* in the right hand corner on Windows, and the RED circle on Mac.

**Comment by willtheorangeguy** [comment]
Exit button is no longer in development.
Closing...
