### ISSUE TITLE
Travis CI Integration

### ISSUE THREAD

**Issue by Derpyface** [Derpyface-Development-Co/Craft-Clash#8]
A lot of projects are using Travis CI integration and it is a good practice that we should adopt too. 

We could add Circle CI if we really wanted to, but in @willtheorangeguy experience, it's not the best.

We just need to take a look at the Travis CI docs and add the `requirements.txt` and `.travis.yml` files.

**Comment by Derpyface** [comment]
You can also get Travis CI to do other things too, such as automatic deployment. Which is another good reason to adopt it.

**Comment by Derpyface** [comment]
I am on it right now!

**Comment by willtheorangeguy** [comment]
Moved to done on Projects and completed on the `master` branch.


Still, work to be done on the `BETv0.0.3` branch.

**Comment by willtheorangeguy** [comment]
Will close as soon as `Beta 0.0.3` is done.

**Comment by Derpyface** [comment]
Completed for both the `BETAv0.0.3` and `master` branches.
